name: Run Jupyter Notebook

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minute
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
  run-notebook-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3'  # specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter

      - name: Run Jupyter Notebook and generate CSV
        run: |
          jupyter nbconvert --to notebook --execute test.ipynb --output /dev/null

      - name: Commit and push CSV to GitHub
        run: |
          git config --global user.email "1900205@eng.asu.edu.eg"
          git config --global user.name "Nayera Hazem"
          git add sum_output.csv
          git commit -m "Add sum_output.csv via GitHub Actions"
          git push
